"""initial event log schema

Revision ID: bf02796cda7e
Revises: 
Create Date: 2026-06-19 13:00:06.758164

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bf02796cda7e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['event_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id', 'name', name='uq_activity_log_name')
    )
    op.create_index(op.f('ix_activities_log_id'), 'activities', ['log_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('case_key', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['event_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id', 'case_key', name='uq_case_log_key')
    )
    op.create_index(op.f('ix_cases_log_id'), 'cases', ['log_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['event_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id', 'name', name='uq_resource_log_name')
    )
    op.create_index(op.f('ix_resources_log_id'), 'resources', ['log_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lifecycle', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_id'], ['event_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_activity_id'), 'events', ['activity_id'], unique=False)
    op.create_index(op.f('ix_events_case_id'), 'events', ['case_id'], unique=False)
    op.create_index('ix_events_case_timestamp', 'events', ['case_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_log_id'), 'events', ['log_id'], unique=False)
    op.create_index('ix_events_log_timestamp', 'events', ['log_id', 'timestamp'], unique=False)
    op.create_table('attributes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_event_id'), 'attributes', ['event_id'], unique=False)
    op.create_index('ix_attributes_event_key', 'attributes', ['event_id', 'key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attributes_event_key', table_name='attributes')
    op.drop_index(op.f('ix_attributes_event_id'), table_name='attributes')
    op.drop_table('attributes')
    op.drop_index('ix_events_log_timestamp', table_name='events')
    op.drop_index(op.f('ix_events_log_id'), table_name='events')
    op.drop_index('ix_events_case_timestamp', table_name='events')
    op.drop_index(op.f('ix_events_case_id'), table_name='events')
    op.drop_index(op.f('ix_events_activity_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_resources_log_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_cases_log_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_activities_log_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
