"""add auth, workspaces, and workspace_id on event_logs

Revision ID: baacbc78f6cf
Revises: bf02796cda7e
Create Date: 2026-06-19 13:30:48.722055

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'baacbc78f6cf'
down_revision: str | None = 'bf02796cda7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.add_column('event_logs', sa.Column('workspace_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_event_logs_workspace_id'), 'event_logs', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'event_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_logs', type_='foreignkey')
    op.drop_index(op.f('ix_event_logs_workspace_id'), table_name='event_logs')
    op.drop_column('event_logs', 'workspace_id')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
